"""One-off generation for the Home tab: the loop's renderer, driven by hand.

The automatic loop and this share everything below the decision-making - the same
workflow patching, the same LoRA handling, the same reference plumbing - so an image
made here and an image made in round 3 of a job come out of the same pipeline. What
differs is who chooses the next set of parameters: here, the person.

A request may carry up to two reference images:
  style : what the character and drawing style should look like. Fed to the IP-Adapter,
          which conditions the model on the image itself rather than on a description of
          it, and/or used as the img2img starting point.
  pose  : where the limbs should go. Turned into a skeleton and fed to the pose
          ControlNet, exactly as the loop's pose library does.
With one reference and "separate pose" off, that single image plays both parts.

Runs are saved under runs/manual/<timestamp>/ so anything generated by hand can be
opened, repainted or handed to a job later.

Generations don't run on the request that asks for them: they go into a queue (one
worker, oldest first), so the Home tab is free again at once and more can be queued
while one renders. Auto-fix requests from History use the same queue. A waiting task
can be removed; a running one is cancelled, its ComfyUI render included.
"""

from __future__ import annotations

import base64
import json
import threading
import time
import traceback
import uuid
from pathlib import Path

from PIL import Image

from . import autofix as autofix_mod
from . import pose as pose_mod
from . import upscale as upscale_mod
from .comfy import Cancelled, ComfyClient
from .params import MODES, GenParams
from .sizes import fit_to, output_size
from .targets import Target, Targets, prompt_parts
from .workflow import Workflows

JOBS: dict[str, dict] = {}       # task id -> public state (what the UI polls)
_REQS: dict[str, dict] = {}      # task id -> its request (with images; never sent back)
_ORDER: list[str] = []           # waiting and running task ids, oldest first
_LOCK = threading.Lock()
_WAKE = threading.Condition(_LOCK)
_CTX: dict = {}
_worker: threading.Thread | None = None
MAX_FINISHED = 12                # finished tasks kept for the Queue tab
FINISHED = ("done", "error", "cancelled")


def configure(*, root: Path, rel_url, load_config, prepare, fix_target) -> None:
    """Set by the server: where things live, how to read settings, prepare() to make sure
    ComfyUI is up (raises if not), and fix_target(run) -> what auto-fix needs for a run."""
    _CTX.update(root=root, rel_url=rel_url, load_config=load_config, prepare=prepare, fix_target=fix_target)


def _set(gen_id: str, **fields) -> None:
    with _LOCK:
        JOBS.setdefault(gen_id, {}).update(fields)


def active_runs() -> set[str]:
    """Folder names (under runs/manual) of generations still in progress."""
    with _LOCK:
        return {j["run"] for j in JOBS.values() if j.get("status") not in FINISHED and j.get("run")}


def busy_targets() -> set[str]:
    """History entries ("manual/<run>" or a loop run) with an auto-fix or upscale waiting or running."""
    with _LOCK:
        return {j["target"] for j in JOBS.values() if j.get("kind") in ("autofix", "upscale")
                and j.get("status") not in FINISHED and j.get("target")}


def status(gen_id: str) -> dict | None:
    with _LOCK:
        job = JOBS.get(gen_id)
        return _public(job) if job else None


def _public(job: dict) -> dict:
    out = {k: v for k, v in job.items() if not k.startswith("_")}
    if job.get("status") == "running" and job.get("run_started"):
        out["elapsed"] = round(time.time() - job["run_started"], 1)
    return out


def queue_status() -> list[dict]:
    """Running and waiting tasks in order, then the most recently finished."""
    with _LOCK:
        live = [_public(JOBS[i]) for i in _ORDER]
        for n, t in enumerate(x for x in live if x["status"] == "waiting"):
            t["position"] = n + 1
        done = sorted((j for j in JOBS.values() if j.get("status") in FINISHED and not j.get("dismissed")),
                      key=lambda j: j.get("finished") or 0, reverse=True)[:MAX_FINISHED]
        return live + [_public(j) for j in done]


def _enqueue(kind: str, req: dict, **fields) -> str:
    global _worker
    gen_id = uuid.uuid4().hex[:12]
    with _WAKE:
        JOBS[gen_id] = {"id": gen_id, "kind": kind, "status": "waiting", "state": "waiting",
                        "created": time.time(), "images": [], "error": None, **fields}
        _REQS[gen_id] = req
        _ORDER.append(gen_id)
        finished = [i for i, j in JOBS.items() if j.get("status") in FINISHED]
        for old in finished[:-MAX_FINISHED * 2]:
            JOBS.pop(old, None)
        if _worker is None or not _worker.is_alive():
            _worker = threading.Thread(target=_worker_loop, daemon=True, name="generation-queue")
            _worker.start()
        _WAKE.notify_all()
    return gen_id


def start(req: dict) -> str:
    """Queue a generation; returns its task id (see status() / queue_status()).

    A rerun of a History entry (see rerun_request) renders into cache/reruns/ instead of
    runs/manual/, so it doesn't add a History entry of its own."""
    label = (req.get("positive") or req.get("description") or "").replace("\n", " ").strip()
    return _enqueue("generate", req, label=label[:140] or "from the reference image",
                    estimate=req.get("estimate"), rerun=bool(req.get("_rerun")),
                    autofix=bool(req.get("autofix")), upscale=bool(req.get("upscale")),
                    batch=int(req.get("batch_size") or 1),
                    has_reference=bool(req.get("style_b64")))


def _image_names(folder: Path, images: list[str]) -> list[str]:
    """The names that are images directly in `folder`. A name with a path in it
    ("../../config.json") is refused: the result is written next to its source."""
    return [n for n in images
            if isinstance(n, str) and n == Path(n).name and not n.startswith(".")
            and Path(n).suffix.lower() in (".png", ".jpg", ".jpeg", ".webp") and (folder / n).is_file()]


def start_autofix(run: str, images: list[str]) -> str:
    """Queue auto-fix for images of a History entry (run: "manual/<run>" or a loop run)."""
    target = _CTX["fix_target"](run)            # fails now, not later, for a bad run name
    names = _image_names(target["dir"], images)
    if not names:
        raise FileNotFoundError("no such image in that run")
    return _enqueue("autofix", {"run": run, "images": names},
                    label=f"{len(names)} image{'s' if len(names) > 1 else ''} of {run.removeprefix('manual/')}",
                    target=run, sources=names)


def start_upscale(run: str, images: list[str]) -> str:
    """Queue upscaling for images of a History entry (each image's auto-fixed version is
    upscaled if it has one; see upscale.best_version)."""
    target = _CTX["fix_target"](run)
    names = _image_names(target["dir"], images)
    if not names:
        raise FileNotFoundError("no such image in that run")
    return _enqueue("upscale", {"run": run, "images": names},
                    label=f"{len(names)} image{'s' if len(names) > 1 else ''} of {run.removeprefix('manual/')}",
                    target=run, sources=names)


def remove(gen_id: str) -> dict:
    """Take a task out of the queue: a waiting one is dropped, a running one cancelled,
    a finished one hidden from the list."""
    with _WAKE:
        job = JOBS.get(gen_id)
        if not job:
            raise KeyError(gen_id)
        if job["status"] == "waiting":
            _ORDER.remove(gen_id)
            _REQS.pop(gen_id, None)
            job.update(status="cancelled", state="removed before it started", finished=time.time(), dismissed=True)
        elif job["status"] == "running":
            job["_cancel"] = True
            job["state"] = "cancelling…"
        else:
            job["dismissed"] = True
        return _public(job)


def clear_finished() -> None:
    with _LOCK:
        for j in JOBS.values():
            if j.get("status") in FINISHED:
                j["dismissed"] = True


def _worker_loop() -> None:
    while True:
        with _WAKE:
            while not any(JOBS[i]["status"] == "waiting" for i in _ORDER):
                _WAKE.wait()
            gen_id = next(i for i in _ORDER if JOBS[i]["status"] == "waiting")
            JOBS[gen_id].update(status="running", state="starting", run_started=time.time())
            req = _REQS[gen_id]
        stop = lambda: bool(JOBS[gen_id].get("_cancel"))
        try:
            _CTX["prepare"]()
            if stop():
                raise Cancelled()
            if JOBS[gen_id]["kind"] == "autofix":
                _run_autofix(gen_id, req, stop)
            elif JOBS[gen_id]["kind"] == "upscale":
                _run_upscale(gen_id, req, stop)
            else:
                _run(gen_id, _CTX["load_config"](), req, _CTX["root"], _CTX["rel_url"], stop)
        except Cancelled:
            _set(gen_id, status="cancelled", state="cancelled", finished=time.time())
        except Exception as e:  # _run records its own errors; this catches the rest
            if JOBS[gen_id].get("status") == "running":
                _set(gen_id, status="error", state="error", error=f"{type(e).__name__}: {e}", finished=time.time())
        finally:
            with _WAKE:
                if gen_id in _ORDER:
                    _ORDER.remove(gen_id)
                _REQS.pop(gen_id, None)


def _save_upload(b64: str, dest: Path) -> Path:
    dest.parent.mkdir(parents=True, exist_ok=True)
    raw = base64.b64decode(b64.split(",", 1)[-1])
    dest.write_bytes(raw)
    return dest


def rerun_request(root: Path, run: str) -> dict:
    """The request that reproduces a History entry (runs/manual/<run>) exactly: its saved
    settings with the prompts, LoRAs and size it actually rendered with (the LLM may have
    written the prompts; "auto" size was resolved) and its saved reference images."""
    base = (root / "runs" / "manual").resolve()
    d = (base / run.removeprefix("manual/")).resolve()
    if d.parent != base or not (d / "run.json").is_file():
        raise FileNotFoundError(run)
    rec = json.loads((d / "run.json").read_text(encoding="utf-8"))
    req = dict(rec.get("request") or {})
    if not rec.get("positive"):
        raise ValueError("that generation has no saved prompt to rerun")
    req.update(positive=rec["positive"], negative=rec.get("negative", ""), description="",
               loras=[{"name": n, "strength": w} for n, w in rec.get("loras") or []],
               _rerun=run)
    if rec.get("size"):
        req["size"] = rec["size"]
    for field, name in (("style_b64", rec.get("reference") or "reference.png"),
                        ("subject_b64", rec.get("subject_reference")),
                        ("pose_b64", rec.get("pose_reference"))):
        f = d / name if name else None
        req[field] = ("data:image/png;base64," + base64.b64encode(f.read_bytes()).decode()) if f and f.is_file() else None
    return req


def _prune_reruns(base: Path, keep: int = 10) -> None:
    """Reruns are scratch: keep only the most recent few."""
    import shutil
    old = sorted((d for d in base.glob("*") if d.is_dir()), reverse=True)[keep - 1:]
    for d in old:
        if d.name not in active_runs():
            shutil.rmtree(d, ignore_errors=True)


def _write_record(run_dir: Path, record: dict) -> None:
    """runs/manual/<run>/run.json: what History shows. Written when the generation starts
    and again when it ends, so a failed or interrupted one is listed too."""
    try:
        (run_dir / "run.json").write_text(json.dumps(record, indent=1), encoding="utf-8")
    except OSError:
        pass


def _run(gen_id: str, cfg: dict, req: dict, root: Path, rel_url, stop) -> None:
    t0 = time.time()
    base = root / "cache" / "reruns" if req.get("_rerun") else root / "runs" / "manual"
    run_dir = base / f"{time.strftime('%Y%m%d-%H%M%S')}_{gen_id[:6]}"
    if req.get("_rerun"):
        _prune_reruns(base)
    _set(gen_id, run=run_dir.name, history=None if req.get("_rerun") else f"manual/{run_dir.name}")

    def check():
        if stop():
            raise Cancelled()

    record = {"status": "running", "started": time.strftime("%Y-%m-%d %H:%M:%S"),
              "request": {k: v for k, v in req.items() if not k.endswith("_b64")},
              "positive": req.get("positive", ""), "negative": req.get("negative", ""),
              "batch": int(req.get("batch_size") or 1), "images": []}
    try:
        run_dir.mkdir(parents=True, exist_ok=True)
        _write_record(run_dir, record)
        comfy = ComfyClient(cfg["comfy_url"])
        flows = Workflows(root / "workflows")

        _use_saved_targets(gen_id, cfg, req, root, record, check)  # a saved style / character, or AI picks
        style = _save_upload(req["style_b64"], run_dir / "reference.png") if req.get("style_b64") else None
        pose_ref = _save_upload(req["pose_b64"], run_dir / "pose_reference.png") if req.get("pose_b64") else None
        subject = _save_upload(req["subject_b64"], run_dir / "subject.png") if req.get("subject_b64") else None
        main = subject or style  # what img2img starts from and "auto" size follows
        # Separate style / subject / pose targets (targets.py). One image and no texts is the
        # classic one-reference generation: that image stands for style, subject and prompt.
        tg = Targets(style=Target(style, (req.get("style_text") or "").strip()),
                     subject=Target(subject, (req.get("subject_text") or "").strip()),
                     pose=Target(pose_ref, (req.get("pose_text") or "").strip()))
        split = (subject is not None and style is not None) or any(t.text for _, t in tg.items())
        if split:
            record["targets"] = tg.to_dict()
        # A saved pose from the library stands in for a pose reference image.
        saved_pose = (req.get("pose_library") or "").strip()
        if saved_pose == "auto":  # the LLM picks one that fits, or none
            check()
            _set(gen_id, state="choosing a pose")
            saved_pose = _pick_pose(gen_id, cfg, req, main, root, record)
        if pose_ref is None and not saved_pose and req.get("pose_from_style") and main is not None:
            pose_ref = main
        pose_note = ""
        if saved_pose and req.get("pose_control"):  # the prompt should describe the pose that will be imposed
            try:
                pose_note = pose_mod.PoseLibrary(root / "poses").get(saved_pose).get("description", "")
            except FileNotFoundError:
                pass

        positive = (req.get("positive") or "").strip()
        negative = (req.get("negative") or "").strip()
        llm_s = None
        if not positive:
            check()
            _set(gen_id, state="writing the prompt")
            t_llm = time.time()
            from .backends import make_backend
            from .prompter import write_prompt
            from .lora_picker import prompt_notes
            from .runner import lora_library
            picks = tuple((l["name"], float(l.get("strength", 0.8))) for l in req.get("loras") or [])
            written = write_prompt(make_backend(cfg["judge"]), req.get("description", ""), "", negative,
                                   flows.default("positive"), flows.default("negative"),
                                   reference=None if split else main,
                                   max_side=cfg["judge"].get("image_max_side", 512),
                                   lora_notes=prompt_notes(lora_library(cfg), picks) if picks else "",
                                   pose_note=pose_note, targets=prompt_parts(tg) if split else None)
            positive, negative = written["positive"], written["negative"]
            llm_s = round(time.time() - t_llm, 1)
            _set(gen_id, positive=positive, negative=negative, prompt_notes=written.get("notes", ""))

        # "auto" follows the shape of the pose the ControlNet will follow (so the skeleton
        # isn't cropped), else the main reference's.
        shape = (_pose_source(saved_pose, pose_ref, root) if req.get("pose_control") else None) or main
        size = (tuple(req["size"]) if isinstance(req.get("size"), (list, tuple))
                else output_size(req.get("size") or "auto", shape, flows.workflow_size())
                if shape else _parse_or_workflow(req.get("size"), flows))
        ip_on = req.get("ipadapter") or req.get("subject_ip") or req.get("style_ip")
        mode = req.get("mode") or ("img2img_reference" if main and not ip_on else "txt2img")
        if main is None and MODES.get(mode, (False,))[0]:
            mode = "txt2img"  # img2img chosen, but there's no reference to start from
        p = GenParams(
            mode=mode,
            positive=positive, negative=negative,
            seed=int(req.get("seed") or 0), steps=int(req.get("steps") or 30),
            cfg=float(req.get("cfg") or 5.5), sampler_name=req.get("sampler_name") or "dpmpp_2m",
            scheduler=req.get("scheduler") or "karras", denoise=float(req.get("denoise") or 1.0),
            loras=tuple((l["name"], float(l.get("strength", 0.8))) for l in req.get("loras") or []),
        )
        if req.get("ai_settings"):
            check()
            _set(gen_id, state="choosing sampler settings")
            p = _ai_settings(gen_id, cfg, req, comfy, flows, p, size, record)

        check()
        _set(gen_id, state="uploading", params=_describe(p, size))
        # img2img encodes the loaded image as it is, so it's fitted to the output size first
        # (as jobs do), with transparency flattened: the workflow reads alpha as a mask.
        # With no reference, LoadImage still gets a real file: ComfyUI validates it even
        # though txt2img never reads it, and the image saved in the workflow may only exist
        # in another machine's input folder. A blank placeholder is uploaded instead.
        if main is None:
            loaded = run_dir / "no_reference.png"
            Image.new("RGB", (64, 64), (128, 128, 128)).save(loaded)
        else:
            loaded = fit_to(main, size, run_dir / "reference_input.png")
        image_name = comfy.upload_image(loaded, f"manual/{run_dir.name}")

        control = None
        if (pose_ref is not None or saved_pose) and req.get("pose_control"):
            _set(gen_id, state="reading the pose")
            skeleton = (_library_pose(saved_pose, size, run_dir, cfg, root) if saved_pose
                        else _pose_image(pose_ref, size, run_dir, cfg))
            if skeleton is not None:
                cn = cfg.get("controlnet", {})
                control = {"model": cn.get("model", "xinsir_union_sdxl_promax.safetensors"),
                           "image": comfy.upload_image(skeleton, f"manual/{run_dir.name}"),
                           "type": "openpose",
                           "strength": float(req.get("pose_strength") or cn.get("pose_strength", 0.6)),
                           "start": 0.0, "end": float(req.get("pose_end") or cn.get("pose_end", 0.8))}
            else:
                _set(gen_id, warning="no person found in the pose reference; pose control skipped")

        ipa = None
        ip_cfg = cfg.get("ipadapter", {})
        if req.get("subject_ip") or req.get("style_ip"):
            # The subject image carries the character (linear), the style image the look
            # (style transfer); chained, see workflow._add_ipadapter.
            ipa = []
            for role, img, weight, wtype in (
                    ("subject", subject if req.get("subject_ip") else None,
                     req.get("subject_ip_weight") or ip_cfg.get("subject_weight", 0.6), ip_cfg.get("weight_type", "linear")),
                    ("style", style if req.get("style_ip") else None,
                     req.get("style_ip_weight") or ip_cfg.get("style_weight", 0.5),
                     ip_cfg.get("style_weight_type", "style transfer"))):
                if img is not None and float(weight) > 0:
                    ipa.append({"image": comfy.upload_image(img, f"manual/{run_dir.name}"), "role": role,
                                "preset": req.get("ip_preset") or ip_cfg.get("preset", "PLUS (high strength)"),
                                "weight": float(weight), "weight_type": wtype, "start": 0.0,
                                "end": float(req.get("ip_end") or ip_cfg.get("end", 1.0))})
            ipa = ipa or None
        elif style is not None and req.get("ipadapter"):  # a request from before the separate targets
            ip = cfg.get("ipadapter", {})
            # The whole reference, not the copy cropped to the output's shape.
            ipa = {"image": comfy.upload_image(style, f"manual/{run_dir.name}"),
                   "preset": req.get("ip_preset") or ip.get("preset", "PLUS (high strength)"),
                   "weight": float(req.get("ip_weight") or ip.get("weight", 0.8)),
                   "weight_type": req.get("ip_weight_type") or ip.get("weight_type", "linear"),
                   "start": 0.0, "end": float(req.get("ip_end") or ip.get("end", 1.0))}

        graph = flows.build(p, image_name, batch_size=int(req.get("batch_size") or 1),
                            checkpoint=req.get("checkpoint") or None, size=size,
                            control=control, ipadapter=ipa)
        record.update(positive=p.positive, negative=p.negative, params=_describe(p, size),
                      loras=[list(l) for l in p.loras], size=list(size),
                      reference="reference.png" if style else None,
                      subject_reference="subject.png" if subject else None,
                      pose_reference=pose_ref.name if pose_ref and pose_ref not in (style, subject) else None,
                      ipadapter=ipa, control=control)
        _write_record(run_dir, record)
        check()
        _set(gen_id, state="rendering", queued_at=time.time())
        t_render = time.time()
        prompt_id = comfy.queue(graph)
        history = comfy.wait([prompt_id], should_stop=stop)
        blobs = comfy.fetch_images(history[prompt_id], flows.output_node)
        images = []
        for i, blob in enumerate(blobs):
            out = run_dir / f"image_{i + 1:02d}.png"
            out.write_bytes(blob)
            images.append(rel_url(out))
        render_s = time.time() - t_render
        record.update(images=[Path(u).name for u in images], batch=len(images))
        _write_record(run_dir, record)
        _set(gen_id, images=images)
        fixed = []
        if req.get("autofix") and images and not req.get("_rerun"):
            fixed = _autofix_images(gen_id, cfg, comfy, flows, run_dir, [run_dir / Path(u).name for u in images],
                                    p, p.positive, req.get("checkpoint") or None, stop)
            errors = [f["error"] for f in fixed if f.get("error")]
            if errors:
                _set(gen_id, warning=f"auto-fix failed for {len(errors)} image(s): {errors[0]}")
        if req.get("upscale") and images and not req.get("_rerun"):
            ups = _upscale_images(gen_id, cfg, comfy, flows, run_dir, [Path(u).name for u in images], p, p.positive,
                                  req.get("checkpoint") or None, stop, rel_url)
            errors = [u["error"] for u in ups if u.get("error")]
            if errors:
                _set(gen_id, warning=f"upscaling failed for {len(errors)} image(s): {errors[0]}")
        record.update(status="done",
                      finished=time.strftime("%Y-%m-%d %H:%M:%S"),
                      timing={"total_s": round(time.time() - t0, 1), "render_s": round(render_s, 1),
                              "llm_s": llm_s, **_work(p, size, len(images), ipa, control)})
        _write_record(run_dir, record)
        _set(gen_id, status="done", state="done", images=images, fixed=fixed, finished=time.time(),
             reference=rel_url(style) if style else None,
             pose_reference=rel_url(pose_ref) if pose_ref and pose_ref != style else None)
    except Cancelled:
        # Removed from the queue while running: nothing worth keeping unless images came back.
        import shutil
        if not any(run_dir.glob("image_*.png")):
            shutil.rmtree(run_dir, ignore_errors=True)
            _set(gen_id, history=None)
        else:  # cancelled while auto-fixing or upscaling: the render itself is finished and good
            record.update(status="done", finished=time.strftime("%Y-%m-%d %H:%M:%S"), note="finishing pass cancelled")
            _write_record(run_dir, record)
        raise
    except Exception as e:
        _set(gen_id, status="error", state="error", error=f"{type(e).__name__}: {e}", finished=time.time())
        record.update(status="error", error=f"{type(e).__name__}: {e}",
                      finished=time.strftime("%Y-%m-%d %H:%M:%S"))
        _write_record(run_dir, record)
        try:
            run_dir.mkdir(parents=True, exist_ok=True)
            (run_dir / "error.txt").write_text(traceback.format_exc(), encoding="utf-8")
        except OSError:
            pass


def _autofix_images(gen_id: str, cfg: dict, comfy, flows, run_dir: Path, sources: list[Path], params: GenParams,
                    positive: str, checkpoint: str | None, stop) -> list[dict]:
    """Auto-fix each image of a run in turn; returns [{"source", "fixed", ...}] as URLs."""
    from .backends import make_backend
    rel_url = _CTX["rel_url"]
    backend = make_backend(cfg["judge"])
    upload = lambda path: comfy.upload_image(path, f"manual/{run_dir.name}")
    out = []
    for n, src in enumerate(sources, 1):
        prefix = f"auto-fixing image {n} of {len(sources)}" if len(sources) > 1 else "auto-fixing"
        _set(gen_id, state=prefix)
        try:
            res = autofix_mod.run_and_record(
                src, params, run_dir=run_dir, backend=backend, comfy=comfy, flows=flows, cfg=cfg,
                checkpoint=checkpoint, positive=positive, upload=upload, log=lambda m: None,
                stage=lambda text: _set(gen_id, state=f"{prefix}: {text}"), should_stop=stop)
        except Cancelled:
            raise
        except Exception as e:  # auto-fix is optional: one image failing doesn't stop the others
            out.append({"source": rel_url(src), "fixed": None, "found": 0, "left": 0, "kept_rounds": 0,
                        "error": f"{type(e).__name__}: {str(e)[:200]}"})
            _set(gen_id, fixed=list(out))
            continue
        out.append({"source": rel_url(src), "fixed": rel_url(res["fixed"]) if res["fixed"] else None,
                    "found": len(res["issues_found"]), "left": len(res["issues_left"]),
                    "kept_rounds": sum(1 for r in res["rounds"] if r["kept"])})
        _set(gen_id, fixed=list(out))
    return out


def _run_autofix(gen_id: str, req: dict, stop) -> None:
    """A queued auto-fix of History images (see start_autofix)."""
    cfg = _CTX["load_config"]()
    t = _CTX["fix_target"](req["run"])
    comfy = ComfyClient(cfg["comfy_url"])
    flows = Workflows(_CTX["root"] / "workflows")
    sources = [t["dir"] / n for n in req["images"]]
    _set(gen_id, images=[_CTX["rel_url"](s) for s in sources], history=req["run"])
    fixed = _autofix_images(gen_id, cfg, comfy, flows, t["dir"], sources, t["params"], t["positive"],
                            t["checkpoint"], stop)
    errors = [f["error"] for f in fixed if f.get("error")]
    if errors and len(errors) == len(fixed):
        _set(gen_id, status="error", state="error", error=errors[0], fixed=fixed, finished=time.time())
    else:
        _set(gen_id, status="done", state="done", fixed=fixed, finished=time.time(),
             warning=f"{len(errors)} image(s) failed: {errors[0]}" if errors else None)


def _upscale_images(gen_id: str, cfg: dict, comfy, flows, run_dir: Path, names: list[str], params: GenParams,
                    positive: str, checkpoint: str | None, stop, rel_url=None) -> list[dict]:
    """Upscale each image of a run in turn (its auto-fixed version if it has one);
    returns [{"source", "upscaled", "size"}] as URLs."""
    rel_url = rel_url or _CTX["rel_url"]
    upload = lambda path: comfy.upload_image(path, f"manual/{run_dir.name}")
    out = []
    for n, name in enumerate(names, 1):
        prefix = f"upscaling image {n} of {len(names)}" if len(names) > 1 else "upscaling"
        _set(gen_id, state=prefix)
        try:
            res = upscale_mod.run_and_record(
                name, params, run_dir=run_dir, comfy=comfy, flows=flows, cfg=cfg, checkpoint=checkpoint,
                positive=positive, upload=upload, stage=lambda text: _set(gen_id, state=f"{prefix}: {text}"),
                should_stop=stop)
        except Cancelled:
            raise
        except Exception as e:  # optional: one image failing doesn't stop the others
            out.append({"source": rel_url(run_dir / name), "upscaled": None, "error": f"{type(e).__name__}: {str(e)[:200]}"})
            _set(gen_id, upscaled=list(out))
            continue
        out.append({"source": rel_url(run_dir / name), "upscaled": rel_url(res["final"]), "size": res["size"]})
        _set(gen_id, upscaled=list(out))
    return out


def _run_upscale(gen_id: str, req: dict, stop) -> None:
    """A queued upscale of History images (see start_upscale)."""
    cfg = _CTX["load_config"]()
    t = _CTX["fix_target"](req["run"])
    comfy = ComfyClient(cfg["comfy_url"])
    flows = Workflows(_CTX["root"] / "workflows")
    _set(gen_id, images=[_CTX["rel_url"](t["dir"] / n) for n in req["images"]], history=req["run"])
    ups = _upscale_images(gen_id, cfg, comfy, flows, t["dir"], req["images"], t["params"], t["positive"],
                          t["checkpoint"], stop)
    errors = [u["error"] for u in ups if u.get("error")]
    if errors and len(errors) == len(ups):
        _set(gen_id, status="error", state="error", error=errors[0], upscaled=ups, finished=time.time())
    else:
        _set(gen_id, status="done", state="done", upscaled=ups, finished=time.time(),
             warning=f"{len(errors)} image(s) failed: {errors[0]}" if errors else None)


def manual_fix_target(root: Path, run: str) -> dict:
    """What auto-fix needs for a Home generation in History: its folder, the settings it
    was made with, and the prompt as rendered."""
    base = (root / "runs" / "manual").resolve()
    d = (base / run.removeprefix("manual/")).resolve()
    if d.parent != base or not (d / "run.json").is_file():
        raise FileNotFoundError(run)
    rec = json.loads((d / "run.json").read_text(encoding="utf-8"))
    q = rec.get("request") or {}
    params = GenParams(positive=rec.get("positive", ""), negative=rec.get("negative", ""),
                       seed=int(q.get("seed") or 0), steps=int(q.get("steps") or 30), cfg=float(q.get("cfg") or 5.5),
                       sampler_name=q.get("sampler_name") or "dpmpp_2m", scheduler=q.get("scheduler") or "karras",
                       loras=tuple((n, float(w)) for n, w in rec.get("loras") or []))
    return {"dir": d, "params": params, "positive": rec.get("positive", ""),
            "checkpoint": q.get("checkpoint") or None, "images": rec.get("images") or []}


def _use_saved_targets(gen_id: str, cfg: dict, req: dict, root: Path, record: dict, check) -> None:
    """A saved style or character chosen for a target (or "auto": the LLM picks one) becomes
    that target's image, and its tags its words when none were typed. The record's request
    keeps the resolved name, so a History rerun uses the same one without asking again."""
    from . import reflib
    notes = []
    for role in ("style", "subject"):
        value = (req.get(f"{role}_library") or "").strip()
        if not value:
            continue
        backend = None
        if value == "auto":
            check()
            _set(gen_id, state=f"choosing a {reflib.ROLE_KIND[role]}")
            from .backends import make_backend
            backend = make_backend(cfg["judge"])
        try:
            got = reflib.resolve(root, role, value, backend=backend, description=req.get("description", ""),
                                 positive=req.get("positive", ""), max_side=cfg["judge"].get("image_max_side", 512))
        except Cancelled:
            raise
        except Exception as e:
            _set(gen_id, warning=f"choosing a {reflib.ROLE_KIND[role]} failed ({str(e)[:160]})")
            continue
        if got and got.get("pick"):
            record[f"{role}_pick"] = {"pick": got["pick"]["pick"], "reason": got["pick"]["reason"]}
            notes.append(f"{reflib.ROLE_KIND[role]}: {got['pick']['pick'] or 'none fits'}"
                         + (f" ({got['pick']['reason']})" if got["pick"]["reason"] else ""))
        record["request"][f"{role}_library"] = (got or {}).get("name") or ""
        if not got or not got.get("image"):
            continue
        req[f"{role}_b64"] = "data:image/png;base64," + base64.b64encode(Path(got["image"]).read_bytes()).decode()
        if not (req.get(f"{role}_text") or "").strip() and got["description"]:
            req[f"{role}_text"] = got["description"]
    if notes:
        _set(gen_id, library_notes="LLM chose " + "; ".join(notes))


def _pick_pose(gen_id: str, cfg: dict, req: dict, style: Path | None, root: Path, record: dict) -> str:
    """Pose "AI picks" on Home: the saved pose the LLM finds fits (pose_picker), or "" for
    none. A pick turns pose control on; the record's request gets the picked name, so a
    History rerun uses the same pose without asking again."""
    from . import pose_picker
    from .backends import make_backend
    if not pose_mod.available():
        _set(gen_id, warning="AI pose picking needs rtmlib (pip install rtmlib); no pose used")
        return ""
    try:
        from_image = not (req.get("description") or "").strip() and not (req.get("positive") or "").strip()
        pick = pose_picker.pick_pose(make_backend(cfg["judge"]), pose_picker.library_menu(pose_mod.PoseLibrary(root / "poses")),
                                     description=req.get("description", ""), positive=req.get("positive", ""),
                                     reference=style if from_image else None,
                                     max_side=cfg["judge"].get("image_max_side", 512))
    except Cancelled:
        raise
    except Exception as e:
        _set(gen_id, warning=f"choosing a pose failed ({str(e)[:160]}); no pose used")
        return ""
    record["pose_pick"] = {"pose": pick["pose"], "reason": pick["reason"], "considered": pick["considered"]}
    record["request"].update(pose_library=pick["pose"] or "", pose_control=bool(pick["pose"]) or bool(req.get("pose_control")))
    if pick["pose"]:
        req["pose_control"] = True
    _set(gen_id, pose_notes=(f"LLM chose the pose {pick['pose']}" if pick["pose"] else "No saved pose fits")
                            + (f": {pick['reason']}" if pick["reason"] else ""))
    return pick["pose"] or ""


def _ai_settings(gen_id: str, cfg: dict, req: dict, comfy, flows: Workflows, p: GenParams,
                 size: tuple[int, int], record: dict) -> GenParams:
    """Let the LLM choose steps/cfg/sampler/scheduler for this render (settings_advisor).
    On failure the form's values stay and a warning says so. The record's request gets the
    chosen values (and ai_settings off), so a History rerun reproduces this render exactly."""
    from dataclasses import replace

    from . import settings_advisor as advisor
    from .backends import make_backend
    from .loras import checkpoint_base
    from .runner import lora_library
    t = time.time()
    current = {k: getattr(p, k) for k in advisor.FIELDS}
    try:
        try:
            samplers = comfy.choices("KSampler", "sampler_name")
            schedulers = comfy.choices("KSampler", "scheduler")
        except Exception:  # can't list them: keep the form's sampler and scheduler
            samplers, schedulers = [p.sampler_name], [p.scheduler]
        ckpt = req.get("checkpoint") or flows.default("checkpoint")
        chosen = advisor.suggest_settings(
            make_backend(cfg["judge"]), checkpoint=ckpt, checkpoint_base=checkpoint_base(ckpt, cfg.get("checkpoint_bases")),
            samplers=samplers, schedulers=schedulers, current=current, positive=p.positive, negative=p.negative,
            description=req.get("description", ""), mode=p.mode, denoise=p.denoise, size=size,
            lora_notes=advisor.lora_lines(lora_library(cfg), p.loras),
            max_side=cfg["judge"].get("image_max_side", 512))
    except Cancelled:
        raise
    except Exception as e:
        _set(gen_id, warning=f"choosing sampler settings failed ({str(e)[:160]}); used the form's settings")
        return p
    picked = {k: chosen[k] for k in advisor.FIELDS}
    record["ai_settings"] = {**picked, "notes": chosen["notes"], "changed": chosen["changed"], "form": current,
                             "seconds": round(time.time() - t, 1)}
    record["request"].update(picked, ai_settings=False)
    _set(gen_id, settings_notes=f"LLM chose {advisor.summary(chosen)}"
                                + (f": {chosen['notes']}" if chosen["notes"] else ""))
    return replace(p, **picked)


def _parse_or_workflow(value, flows: Workflows) -> tuple[int, int]:
    from .sizes import parse_size
    return parse_size(value) or flows.workflow_size() or (1024, 1024)


def _library_pose(name: str, size: tuple[int, int], run_dir: Path, cfg: dict, root: Path) -> Path | None:
    """A pose saved in the library (the same ones jobs use), drawn at the output size."""
    try:
        saved = pose_mod.PoseLibrary(root / "poses").get(name)
    except (FileNotFoundError, OSError, ValueError):
        return None
    if not pose_mod.has_body(saved):
        return None
    cn = cfg.get("controlnet", {})
    out = run_dir / "pose_control.png"
    # Keypoints are fractions of the pose's own image: drawn straight onto a frame of
    # another shape they'd be stretched, so they're cropped to it as the image would be.
    fitted = pose_mod.fit(saved, tuple(saved.get("size") or size), size)
    pose_mod.render(fitted, size, hands=cn.get("pose_hands", True),
                    face=cn.get("pose_face", False)).save(out)
    return out


def _pose_source(saved_pose: str, pose_ref: Path | None, root: Path) -> Path | None:
    """The image a pose comes from: the pose reference, or a library pose's source image."""
    if pose_ref is not None:
        return pose_ref
    if saved_pose:
        try:
            src = pose_mod.PoseLibrary(root / "poses").source(saved_pose)
            return src if src.is_file() else None
        except (FileNotFoundError, OSError):
            return None
    return None


def _pose_image(reference: Path, size: tuple[int, int], run_dir: Path, cfg: dict) -> Path | None:
    """The pose reference as an openpose skeleton at the output size."""
    found = pose_mod.detect(reference)
    if not pose_mod.has_body(found):
        return None
    with Image.open(reference) as img:
        src = img.size
    cn = cfg.get("controlnet", {})
    fitted = pose_mod.fit(found, src, size)
    out = run_dir / "pose_control.png"
    pose_mod.render(fitted, size, hands=cn.get("pose_hands", True),
                    face=cn.get("pose_face", False)).save(out)
    return out


def _work(p: GenParams, size: tuple[int, int], batch: int, ipa, control) -> dict:
    """What the render cost depends on: sampled steps x megapixels x images."""
    steps = p.steps * (p.denoise if p.mode != "txt2img" else 1.0)
    mp = size[0] * size[1] / 1e6
    return {"steps": round(steps, 1), "megapixels": round(mp, 3), "images": batch,
            "ipadapter": bool(ipa), "control": bool(control)}


def estimate(root: Path, recent: int = 12) -> dict:
    """Seconds per unit of render work (step x megapixel x image), from the last manual
    renders on this machine; the Home tab turns it into a time estimate. Falls back to a
    rough SDXL figure until there is history."""
    rates, llm = [], []
    for f in sorted((root / "runs" / "manual").glob("*/run.json"), reverse=True)[:60]:
        try:
            rec = json.loads(f.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        t = rec.get("timing") or _timing_from_files(f.parent, rec)
        if not t:
            continue
        work = (t.get("steps") or 0) * (t.get("megapixels") or 0) * (t.get("images") or 0)
        if work and t.get("render_s"):
            extra = 1 + IPADAPTER_COST * bool(t.get("ipadapter")) + CONTROL_COST * bool(t.get("control"))
            rates.append(max(0.05, (t["render_s"] - FIXED_S) / (work * extra)))
        if t.get("llm_s"):
            llm.append(t["llm_s"])
        if len(rates) >= recent:
            break
    median = lambda xs: sorted(xs)[len(xs) // 2] if xs else None
    return {"rate": round(median(rates) or DEFAULT_RATE, 3), "fixed": FIXED_S, "llm": median(llm) or 20,
            "ipadapter": IPADAPTER_COST, "control": CONTROL_COST, "samples": len(rates)}


def _timing_from_files(run_dir: Path, rec: dict) -> dict | None:
    """Older runs have no timing: the folder is named when the render starts and the
    images are written when it ends. Only used when the LLM didn't write the prompt."""
    try:
        start = time.mktime(time.strptime(run_dir.name[:15], "%Y%m%d-%H%M%S"))
        images = list(run_dir.glob("image_*.png"))
        if not images or not rec.get("size") or not (rec.get("request") or {}).get("positive"):
            return None
        end = max(f.stat().st_mtime for f in images)
        fields = dict(x.split("=", 1) for x in rec["params"].split() if "=" in x)
        steps = int(fields["steps"]) * (float(fields["denoise"]) if not rec["params"].startswith("txt2img") else 1)
        w, h = rec["size"]
        return {"render_s": end - start, "steps": steps, "megapixels": w * h / 1e6, "images": len(images),
                "ipadapter": bool(rec.get("ipadapter")), "control": bool(rec.get("control"))}
    except (OSError, ValueError, KeyError, TypeError):
        return None


# Seconds of overhead per render (upload, VAE decode, fetching images), seconds per step
# per megapixel per image for SDXL before any history exists (RTX 2080 Ti on Linux), and
# the extra fraction the IP-Adapter and the pose ControlNet add.
FIXED_S = 4.0
DEFAULT_RATE = 0.6
IPADAPTER_COST = 0.3
CONTROL_COST = 0.4


def _describe(p: GenParams, size: tuple[int, int]) -> str:
    return (f"{p.mode} {size[0]}x{size[1]} seed={p.seed} steps={p.steps} cfg={p.cfg} "
            f"{p.sampler_name}/{p.scheduler} denoise={p.denoise}")
